// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package db

import (
	"context"
	"time"
)

const countBatches = `-- name: CountBatches :one
SELECT count(*) FROM "Batch"
WHERE ($1::text IS NULL OR "manufacturer" = $1)
`

func (q *Queries) CountBatches(ctx context.Context, manufacturer *string) (int64, error) {
	row := q.db.QueryRow(ctx, countBatches, manufacturer)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBatch = `-- name: GetBatch :one
SELECT "batchId", manufacturer, size, "merkleRoot", "physicalBatchId", "metadataCid", "metadataHash", name, "lotCode", "consumedCount", invalid, "txHash", "blockNumber", "createdAt", "updatedAt" FROM "Batch" WHERE "batchId" = $1
`

func (q *Queries) GetBatch(ctx context.Context, batchID int64) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatch, batchID)
	var i Batch
	err := row.Scan(
		&i.BatchID,
		&i.Manufacturer,
		&i.Size,
		&i.MerkleRoot,
		&i.PhysicalBatchID,
		&i.MetadataCID,
		&i.MetadataHash,
		&i.Name,
		&i.LotCode,
		&i.ConsumedCount,
		&i.Invalid,
		&i.TxHash,
		&i.BlockNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndexerCursor = `-- name: GetIndexerCursor :one
SELECT name, "lastBlock", "blockHash", "updatedAt" FROM "IndexerCursor" WHERE "name" = $1
`

func (q *Queries) GetIndexerCursor(ctx context.Context, name string) (IndexerCursor, error) {
	row := q.db.QueryRow(ctx, getIndexerCursor, name)
	var i IndexerCursor
	err := row.Scan(
		&i.Name,
		&i.LastBlock,
		&i.BlockHash,
		&i.UpdatedAt,
	)
	return i, err
}

const listBatches = `-- name: ListBatches :many
SELECT "batchId", manufacturer, size, "merkleRoot", "physicalBatchId", "metadataCid", "metadataHash", name, "lotCode", "consumedCount", invalid, "txHash", "blockNumber", "createdAt", "updatedAt" FROM "Batch"
WHERE ($1::text IS NULL OR "manufacturer" = $1)
ORDER BY "batchId" DESC
LIMIT $3 OFFSET $2
`

type ListBatchesParams struct {
	Manufacturer *string
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listBatches, arg.Manufacturer, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Batch
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.BatchID,
			&i.Manufacturer,
			&i.Size,
			&i.MerkleRoot,
			&i.PhysicalBatchID,
			&i.MetadataCID,
			&i.MetadataHash,
			&i.Name,
			&i.LotCode,
			&i.ConsumedCount,
			&i.Invalid,
			&i.TxHash,
			&i.BlockNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBatchInvalid = `-- name: SetBatchInvalid :execrows
UPDATE "Batch" SET "invalid" = true, "updatedAt" = $1 WHERE "batchId" = $2
`

type SetBatchInvalidParams struct {
	Now     time.Time
	BatchID int64
}

func (q *Queries) SetBatchInvalid(ctx context.Context, arg SetBatchInvalidParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBatchInvalid, arg.Now, arg.BatchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIndexerCursor = `-- name: SetIndexerCursor :exec
INSERT INTO "IndexerCursor" ("name", "lastBlock", "blockHash", "updatedAt")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("name") DO UPDATE SET
    "lastBlock" = EXCLUDED."lastBlock",
    "blockHash" = EXCLUDED."blockHash",
    "updatedAt" = EXCLUDED."updatedAt"
`

type SetIndexerCursorParams struct {
	Name      string
	LastBlock int64
	BlockHash string
	Now       time.Time
}

func (q *Queries) SetIndexerCursor(ctx context.Context, arg SetIndexerCursorParams) error {
	_, err := q.db.Exec(ctx, setIndexerCursor,
		arg.Name,
		arg.LastBlock,
		arg.BlockHash,
		arg.Now,
	)
	return err
}

const upsertBatch = `-- name: UpsertBatch :one
INSERT INTO "Batch" (
    "batchId", "manufacturer", "size", "merkleRoot", "physicalBatchId", "metadataCid",
    "metadataHash", "name", "lotCode", "txHash", "blockNumber", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $12
)
ON CONFLICT ("batchId") DO UPDATE SET
    "name" = COALESCE(EXCLUDED."name", "Batch"."name"),
    "lotCode" = COALESCE(EXCLUDED."lotCode", "Batch"."lotCode"),
    "updatedAt" = EXCLUDED."updatedAt"
RETURNING "batchId", manufacturer, size, "merkleRoot", "physicalBatchId", "metadataCid", "metadataHash", name, "lotCode", "consumedCount", invalid, "txHash", "blockNumber", "createdAt", "updatedAt"
`

type UpsertBatchParams struct {
	BatchID         int64
	Manufacturer    string
	Size            int32
	MerkleRoot      string
	PhysicalBatchID string
	MetadataCID     string
	MetadataHash    string
	Name            *string
	LotCode         *string
	TxHash          string
	BlockNumber     int64
	Now             time.Time
}

// Chain fields are immutable; name and lot code only come from the API, so a
// later indexer upsert must not erase them.
func (q *Queries) UpsertBatch(ctx context.Context, arg UpsertBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, upsertBatch,
		arg.BatchID,
		arg.Manufacturer,
		arg.Size,
		arg.MerkleRoot,
		arg.PhysicalBatchID,
		arg.MetadataCID,
		arg.MetadataHash,
		arg.Name,
		arg.LotCode,
		arg.TxHash,
		arg.BlockNumber,
		arg.Now,
	)
	var i Batch
	err := row.Scan(
		&i.BatchID,
		&i.Manufacturer,
		&i.Size,
		&i.MerkleRoot,
		&i.PhysicalBatchID,
		&i.MetadataCID,
		&i.MetadataHash,
		&i.Name,
		&i.LotCode,
		&i.ConsumedCount,
		&i.Invalid,
		&i.TxHash,
		&i.BlockNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
