// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: misc.sql

package db

import (
	"context"
	"time"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO "AuditLog" ("id", "action", "entityId", "actor", "detail", "createdAt")
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	ID       string
	Action   string
	EntityID *string
	Actor    *string
	Detail   *string
	Now      time.Time
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.Action,
		arg.EntityID,
		arg.Actor,
		arg.Detail,
		arg.Now,
	)
	return err
}

const createCounterfeitReport = `-- name: CreateCounterfeitReport :one
INSERT INTO "CounterfeitReport" ("id", "chainProductId", "note", "reporter", "createdAt")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, "chainProductId", note, reporter, "createdAt"
`

type CreateCounterfeitReportParams struct {
	ID             string
	ChainProductID string
	Note           *string
	Reporter       *string
	Now            time.Time
}

func (q *Queries) CreateCounterfeitReport(ctx context.Context, arg CreateCounterfeitReportParams) (CounterfeitReport, error) {
	row := q.db.QueryRow(ctx, createCounterfeitReport,
		arg.ID,
		arg.ChainProductID,
		arg.Note,
		arg.Reporter,
		arg.Now,
	)
	var i CounterfeitReport
	err := row.Scan(
		&i.ID,
		&i.ChainProductID,
		&i.Note,
		&i.Reporter,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAnalyticsCounter = `-- name: IncrementAnalyticsCounter :one
INSERT INTO "AnalyticsCounter" ("id", "name", "value", "updatedAt")
VALUES ($1, $2, 1, $3)
ON CONFLICT ("name") DO UPDATE SET
    "value" = "AnalyticsCounter"."value" + 1,
    "updatedAt" = EXCLUDED."updatedAt"
RETURNING "name", "value"
`

type IncrementAnalyticsCounterParams struct {
	ID   string
	Name string
	Now  time.Time
}

type IncrementAnalyticsCounterRow struct {
	Name  string
	Value int64
}

func (q *Queries) IncrementAnalyticsCounter(ctx context.Context, arg IncrementAnalyticsCounterParams) (IncrementAnalyticsCounterRow, error) {
	row := q.db.QueryRow(ctx, incrementAnalyticsCounter, arg.ID, arg.Name, arg.Now)
	var i IncrementAnalyticsCounterRow
	err := row.Scan(&i.Name, &i.Value)
	return i, err
}

const listAnalyticsCounters = `-- name: ListAnalyticsCounters :many
SELECT "name", "value" FROM "AnalyticsCounter" ORDER BY "name" ASC
`

type ListAnalyticsCountersRow struct {
	Name  string
	Value int64
}

func (q *Queries) ListAnalyticsCounters(ctx context.Context) ([]ListAnalyticsCountersRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsCounters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalyticsCountersRow
	for rows.Next() {
		var i ListAnalyticsCountersRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterfeitReports = `-- name: ListCounterfeitReports :many
SELECT id, "chainProductId", note, reporter, "createdAt" FROM "CounterfeitReport" ORDER BY "createdAt" DESC, "id" DESC LIMIT $1
`

func (q *Queries) ListCounterfeitReports(ctx context.Context, maxRows int32) ([]CounterfeitReport, error) {
	rows, err := q.db.Query(ctx, listCounterfeitReports, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CounterfeitReport
	for rows.Next() {
		var i CounterfeitReport
		if err := rows.Scan(
			&i.ID,
			&i.ChainProductID,
			&i.Note,
			&i.Reporter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
