// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type ProductStatus string

const (
	ProductStatusCreated       ProductStatus = "Created"
	ProductStatusTransferred   ProductStatus = "Transferred"
	ProductStatusAtPointOfSale ProductStatus = "AtPointOfSale"
	ProductStatusConsumed      ProductStatus = "Consumed"
	ProductStatusInvalid       ProductStatus = "Invalid"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus
	Valid         bool // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

func (e ProductStatus) Valid() bool {
	switch e {
	case ProductStatusCreated,
		ProductStatusTransferred,
		ProductStatusAtPointOfSale,
		ProductStatusConsumed,
		ProductStatusInvalid:
		return true
	}
	return false
}

func AllProductStatusValues() []ProductStatus {
	return []ProductStatus{
		ProductStatusCreated,
		ProductStatusTransferred,
		ProductStatusAtPointOfSale,
		ProductStatusConsumed,
		ProductStatusInvalid,
	}
}

type SupplyRole string

const (
	SupplyRoleManufacturer SupplyRole = "Manufacturer"
	SupplyRoleDistributor  SupplyRole = "Distributor"
	SupplyRolePharmacy     SupplyRole = "Pharmacy"
	SupplyRoleAdmin        SupplyRole = "Admin"
)

func (e *SupplyRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SupplyRole(s)
	case string:
		*e = SupplyRole(s)
	default:
		return fmt.Errorf("unsupported scan type for SupplyRole: %T", src)
	}
	return nil
}

type NullSupplyRole struct {
	SupplyRole SupplyRole
	Valid      bool // Valid is true if SupplyRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSupplyRole) Scan(value interface{}) error {
	if value == nil {
		ns.SupplyRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SupplyRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSupplyRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SupplyRole), nil
}

func (e SupplyRole) Valid() bool {
	switch e {
	case SupplyRoleManufacturer,
		SupplyRoleDistributor,
		SupplyRolePharmacy,
		SupplyRoleAdmin:
		return true
	}
	return false
}

func AllSupplyRoleValues() []SupplyRole {
	return []SupplyRole{
		SupplyRoleManufacturer,
		SupplyRoleDistributor,
		SupplyRolePharmacy,
		SupplyRoleAdmin,
	}
}

type AnalyticsCounter struct {
	ID        string
	Name      string
	Value     int64
	UpdatedAt time.Time
}

type AuditLog struct {
	ID        string
	Action    string
	EntityID  *string
	Actor     *string
	Detail    *string
	CreatedAt time.Time
}

type CounterfeitReport struct {
	ID             string
	ChainProductID string
	Note           *string
	Reporter       *string
	CreatedAt      time.Time
}

type OwnershipEvent struct {
	ID             string
	ProductID      string
	ChainProductID string
	FromAddress    string
	ToAddress      string
	TxHash         string
	BlockNumber    int64
	CreatedAt      time.Time
}

type Product struct {
	ID             string
	ChainProductID string
	OwnerAddress   string
	Status         ProductStatus
	Name           *string
	BatchCode      *string
	MetadataCID    *string
	MetadataHash   *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RoleBinding struct {
	ID        string
	Address   string
	Role      SupplyRole
	CreatedAt time.Time
	UpdatedAt time.Time
}
