// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ownership.sql

package db

import (
	"context"
	"time"
)

const createOwnershipEvent = `-- name: CreateOwnershipEvent :exec
INSERT INTO "OwnershipEvent" (
    "id", "productId", "chainProductId", "fromAddress", "toAddress", "txHash", "blockNumber", "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateOwnershipEventParams struct {
	ID             string
	ProductID      string
	ChainProductID string
	FromAddress    string
	ToAddress      string
	TxHash         string
	BlockNumber    int64
	Now            time.Time
}

func (q *Queries) CreateOwnershipEvent(ctx context.Context, arg CreateOwnershipEventParams) error {
	_, err := q.db.Exec(ctx, createOwnershipEvent,
		arg.ID,
		arg.ProductID,
		arg.ChainProductID,
		arg.FromAddress,
		arg.ToAddress,
		arg.TxHash,
		arg.BlockNumber,
		arg.Now,
	)
	return err
}

const listOwnershipEvents = `-- name: ListOwnershipEvents :many
SELECT "id", "fromAddress", "toAddress", "txHash", "blockNumber", "createdAt"
FROM "OwnershipEvent"
WHERE "productId" = $1
ORDER BY "blockNumber" ASC, "createdAt" ASC
`

type ListOwnershipEventsRow struct {
	ID          string
	FromAddress string
	ToAddress   string
	TxHash      string
	BlockNumber int64
	CreatedAt   time.Time
}

func (q *Queries) ListOwnershipEvents(ctx context.Context, productID string) ([]ListOwnershipEventsRow, error) {
	rows, err := q.db.Query(ctx, listOwnershipEvents, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnershipEventsRow
	for rows.Next() {
		var i ListOwnershipEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromAddress,
			&i.ToAddress,
			&i.TxHash,
			&i.BlockNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownershipEventExists = `-- name: OwnershipEventExists :one
SELECT EXISTS (
    SELECT 1 FROM "OwnershipEvent"
    WHERE "txHash" = $1 AND "chainProductId" = $2
)
`

type OwnershipEventExistsParams struct {
	TxHash         string
	ChainProductID string
}

func (q *Queries) OwnershipEventExists(ctx context.Context, arg OwnershipEventExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownershipEventExists, arg.TxHash, arg.ChainProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
