// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"time"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM "Product"
WHERE ($1::text IS NULL OR "ownerAddress" = $1)
  AND ($2::"ProductStatus" IS NULL OR "status" = $2)
  AND (
    $3::text IS NULL
    OR "name" ILIKE $3
    OR "batchCode" ILIKE $3
    OR "chainProductId" LIKE $3
    OR "id" LIKE $3
  )
`

type CountProductsParams struct {
	Owner   *string
	Status  *ProductStatus
	Pattern *string
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.Owner, arg.Status, arg.Pattern)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO "Product" (
    "id", "chainProductId", "ownerAddress", "status", "name", "batchCode",
    "metadataCid", "metadataHash", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $9
)
RETURNING id, "chainProductId", "ownerAddress", status, name, "batchCode", "metadataCid", "metadataHash", "createdAt", "updatedAt"
`

type CreateProductParams struct {
	ID             string
	ChainProductID string
	OwnerAddress   string
	Status         ProductStatus
	Name           *string
	BatchCode      *string
	MetadataCID    *string
	MetadataHash   *string
	Now            time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.ChainProductID,
		arg.OwnerAddress,
		arg.Status,
		arg.Name,
		arg.BatchCode,
		arg.MetadataCID,
		arg.MetadataHash,
		arg.Now,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ChainProductID,
		&i.OwnerAddress,
		&i.Status,
		&i.Name,
		&i.BatchCode,
		&i.MetadataCID,
		&i.MetadataHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProduct = `-- name: FindProduct :one
SELECT id, "chainProductId", "ownerAddress", status, name, "batchCode", "metadataCid", "metadataHash", "createdAt", "updatedAt" FROM "Product" WHERE "chainProductId" = $1 OR "id" = $1 LIMIT 1
`

func (q *Queries) FindProduct(ctx context.Context, key string) (Product, error) {
	row := q.db.QueryRow(ctx, findProduct, key)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ChainProductID,
		&i.OwnerAddress,
		&i.Status,
		&i.Name,
		&i.BatchCode,
		&i.MetadataCID,
		&i.MetadataHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByChainID = `-- name: GetProductByChainID :one
SELECT id, "chainProductId", "ownerAddress", status, name, "batchCode", "metadataCid", "metadataHash", "createdAt", "updatedAt" FROM "Product" WHERE "chainProductId" = $1
`

func (q *Queries) GetProductByChainID(ctx context.Context, chainProductID string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByChainID, chainProductID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ChainProductID,
		&i.OwnerAddress,
		&i.Status,
		&i.Name,
		&i.BatchCode,
		&i.MetadataCID,
		&i.MetadataHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT "id", "chainProductId", "ownerAddress", "status", "name", "batchCode", "metadataCid", "createdAt"
FROM "Product"
WHERE ($1::text IS NULL OR "ownerAddress" = $1)
  AND ($2::"ProductStatus" IS NULL OR "status" = $2)
  AND (
    $3::text IS NULL
    OR "name" ILIKE $3
    OR "batchCode" ILIKE $3
    OR "chainProductId" LIKE $3
    OR "id" LIKE $3
  )
ORDER BY "createdAt" DESC, "id" DESC
LIMIT $5 OFFSET $4
`

type ListProductsParams struct {
	Owner      *string
	Status     *ProductStatus
	Pattern    *string
	PageOffset int32
	PageLimit  int32
}

type ListProductsRow struct {
	ID             string
	ChainProductID string
	OwnerAddress   string
	Status         ProductStatus
	Name           *string
	BatchCode      *string
	MetadataCID    *string
	CreatedAt      time.Time
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Owner,
		arg.Status,
		arg.Pattern,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainProductID,
			&i.OwnerAddress,
			&i.Status,
			&i.Name,
			&i.BatchCode,
			&i.MetadataCID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByBatch = `-- name: ListProductsByBatch :many
SELECT "chainProductId", "name", "batchCode", "status"
FROM "Product"
WHERE "batchCode" = $1
ORDER BY "createdAt" ASC, "id" ASC
LIMIT 500
`

type ListProductsByBatchRow struct {
	ChainProductID string
	Name           *string
	BatchCode      *string
	Status         ProductStatus
}

func (q *Queries) ListProductsByBatch(ctx context.Context, batchCode *string) ([]ListProductsByBatchRow, error) {
	rows, err := q.db.Query(ctx, listProductsByBatch, batchCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByBatchRow
	for rows.Next() {
		var i ListProductsByBatchRow
		if err := rows.Scan(
			&i.ChainProductID,
			&i.Name,
			&i.BatchCode,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductChainIdentity = `-- name: SetProductChainIdentity :one
UPDATE "Product"
SET "chainProductId" = $1, "ownerAddress" = $2, "updatedAt" = $3
WHERE "id" = $4
RETURNING id, "chainProductId", "ownerAddress", status, name, "batchCode", "metadataCid", "metadataHash", "createdAt", "updatedAt"
`

type SetProductChainIdentityParams struct {
	ChainProductID string
	OwnerAddress   string
	Now            time.Time
	ID             string
}

func (q *Queries) SetProductChainIdentity(ctx context.Context, arg SetProductChainIdentityParams) (Product, error) {
	row := q.db.QueryRow(ctx, setProductChainIdentity,
		arg.ChainProductID,
		arg.OwnerAddress,
		arg.Now,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ChainProductID,
		&i.OwnerAddress,
		&i.Status,
		&i.Name,
		&i.BatchCode,
		&i.MetadataCID,
		&i.MetadataHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setProductStatus = `-- name: SetProductStatus :execrows
UPDATE "Product"
SET "status" = $1, "updatedAt" = $2
WHERE "id" = $3
`

type SetProductStatusParams struct {
	Status ProductStatus
	Now    time.Time
	ID     string
}

func (q *Queries) SetProductStatus(ctx context.Context, arg SetProductStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProductStatus, arg.Status, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProductOwner = `-- name: UpsertProductOwner :one
INSERT INTO "Product" ("id", "chainProductId", "ownerAddress", "status", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT ("chainProductId") DO UPDATE SET
    "ownerAddress" = EXCLUDED."ownerAddress",
    "status" = EXCLUDED."status",
    "updatedAt" = EXCLUDED."updatedAt"
RETURNING "id"
`

type UpsertProductOwnerParams struct {
	ID             string
	ChainProductID string
	OwnerAddress   string
	Status         ProductStatus
	Now            time.Time
}

func (q *Queries) UpsertProductOwner(ctx context.Context, arg UpsertProductOwnerParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertProductOwner,
		arg.ID,
		arg.ChainProductID,
		arg.OwnerAddress,
		arg.Status,
		arg.Now,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertProductStatus = `-- name: UpsertProductStatus :exec
INSERT INTO "Product" ("id", "chainProductId", "ownerAddress", "status", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT ("chainProductId") DO UPDATE SET
    "status" = EXCLUDED."status",
    "updatedAt" = EXCLUDED."updatedAt"
`

type UpsertProductStatusParams struct {
	ID             string
	ChainProductID string
	OwnerAddress   string
	Status         ProductStatus
	Now            time.Time
}

func (q *Queries) UpsertProductStatus(ctx context.Context, arg UpsertProductStatusParams) error {
	_, err := q.db.Exec(ctx, upsertProductStatus,
		arg.ID,
		arg.ChainProductID,
		arg.OwnerAddress,
		arg.Status,
		arg.Now,
	)
	return err
}

const upsertRegisteredProduct = `-- name: UpsertRegisteredProduct :exec
INSERT INTO "Product" (
    "id", "chainProductId", "ownerAddress", "status", "metadataCid", "metadataHash", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7
)
ON CONFLICT ("chainProductId") DO UPDATE SET
    "ownerAddress" = EXCLUDED."ownerAddress",
    "status" = EXCLUDED."status",
    "metadataCid" = EXCLUDED."metadataCid",
    "metadataHash" = EXCLUDED."metadataHash",
    "updatedAt" = EXCLUDED."updatedAt"
`

type UpsertRegisteredProductParams struct {
	ID             string
	ChainProductID string
	OwnerAddress   string
	Status         ProductStatus
	MetadataCID    *string
	MetadataHash   *string
	Now            time.Time
}

func (q *Queries) UpsertRegisteredProduct(ctx context.Context, arg UpsertRegisteredProductParams) error {
	_, err := q.db.Exec(ctx, upsertRegisteredProduct,
		arg.ID,
		arg.ChainProductID,
		arg.OwnerAddress,
		arg.Status,
		arg.MetadataCID,
		arg.MetadataHash,
		arg.Now,
	)
	return err
}
