// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateCounterfeitReport(ctx context.Context, arg CreateCounterfeitReportParams) (CounterfeitReport, error)
	CreateOwnershipEvent(ctx context.Context, arg CreateOwnershipEventParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteRoleBinding(ctx context.Context, arg DeleteRoleBindingParams) (int64, error)
	FindProduct(ctx context.Context, key string) (Product, error)
	GetProductByChainID(ctx context.Context, chainProductID string) (Product, error)
	IncrementAnalyticsCounter(ctx context.Context, arg IncrementAnalyticsCounterParams) (IncrementAnalyticsCounterRow, error)
	ListAnalyticsCounters(ctx context.Context) ([]ListAnalyticsCountersRow, error)
	ListCounterfeitReports(ctx context.Context, maxRows int32) ([]CounterfeitReport, error)
	ListOwnershipEvents(ctx context.Context, productID string) ([]ListOwnershipEventsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListProductsByBatch(ctx context.Context, batchCode *string) ([]ListProductsByBatchRow, error)
	ListRoleBindings(ctx context.Context) ([]RoleBinding, error)
	ListRoleBindingsForAddress(ctx context.Context, address string) ([]RoleBinding, error)
	OwnershipEventExists(ctx context.Context, arg OwnershipEventExistsParams) (bool, error)
	SetProductChainIdentity(ctx context.Context, arg SetProductChainIdentityParams) (Product, error)
	SetProductStatus(ctx context.Context, arg SetProductStatusParams) (int64, error)
	UpsertProductOwner(ctx context.Context, arg UpsertProductOwnerParams) (string, error)
	UpsertProductStatus(ctx context.Context, arg UpsertProductStatusParams) error
	UpsertRegisteredProduct(ctx context.Context, arg UpsertRegisteredProductParams) error
	// Existing bindings are returned untouched, matching Prisma's `upsert` with an empty update.
	UpsertRoleBinding(ctx context.Context, arg UpsertRoleBindingParams) (RoleBinding, error)
}

var _ Querier = (*Queries)(nil)
