// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"
	"time"
)

const deleteRoleBinding = `-- name: DeleteRoleBinding :execrows
DELETE FROM "RoleBinding" WHERE "address" = $1 AND "role" = $2
`

type DeleteRoleBindingParams struct {
	Address string
	Role    SupplyRole
}

func (q *Queries) DeleteRoleBinding(ctx context.Context, arg DeleteRoleBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoleBinding, arg.Address, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPartyProfile = `-- name: GetPartyProfile :one
SELECT "address", "role", "displayName", "region" FROM "RoleBinding"
WHERE "address" = $1
ORDER BY ("role" = 'Pharmacy') DESC, ("displayName" IS NOT NULL) DESC, "role" ASC
LIMIT 1
`

type GetPartyProfileRow struct {
	Address     string
	Role        SupplyRole
	DisplayName *string
	Region      *string
}

// The profile shown for a custodian: a Pharmacy binding wins, then any
// binding with a display name.
func (q *Queries) GetPartyProfile(ctx context.Context, address string) (GetPartyProfileRow, error) {
	row := q.db.QueryRow(ctx, getPartyProfile, address)
	var i GetPartyProfileRow
	err := row.Scan(
		&i.Address,
		&i.Role,
		&i.DisplayName,
		&i.Region,
	)
	return i, err
}

const listRoleBindings = `-- name: ListRoleBindings :many
SELECT id, address, role, "createdAt", "updatedAt", "displayName", region FROM "RoleBinding" ORDER BY "role" ASC, "address" ASC
`

func (q *Queries) ListRoleBindings(ctx context.Context) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listRoleBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleBinding
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsForAddress = `-- name: ListRoleBindingsForAddress :many
SELECT id, address, role, "createdAt", "updatedAt", "displayName", region FROM "RoleBinding" WHERE "address" = $1 ORDER BY "role" ASC
`

func (q *Queries) ListRoleBindingsForAddress(ctx context.Context, address string) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listRoleBindingsForAddress, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleBinding
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoleBinding = `-- name: UpsertRoleBinding :one
INSERT INTO "RoleBinding" ("id", "address", "role", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT ("address", "role") DO UPDATE SET "address" = "RoleBinding"."address"
RETURNING id, address, role, "createdAt", "updatedAt", "displayName", region
`

type UpsertRoleBindingParams struct {
	ID      string
	Address string
	Role    SupplyRole
	Now     time.Time
}

// Existing bindings are returned untouched, matching Prisma's `upsert` with an empty update.
func (q *Queries) UpsertRoleBinding(ctx context.Context, arg UpsertRoleBindingParams) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, upsertRoleBinding,
		arg.ID,
		arg.Address,
		arg.Role,
		arg.Now,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Region,
	)
	return i, err
}

const upsertRoleBindingProfile = `-- name: UpsertRoleBindingProfile :one
INSERT INTO "RoleBinding" ("id", "address", "role", "displayName", "region", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $6)
ON CONFLICT ("address", "role") DO UPDATE SET
    "displayName" = COALESCE(EXCLUDED."displayName", "RoleBinding"."displayName"),
    "region" = COALESCE(EXCLUDED."region", "RoleBinding"."region"),
    "updatedAt" = EXCLUDED."updatedAt"
RETURNING id, address, role, "createdAt", "updatedAt", "displayName", region
`

type UpsertRoleBindingProfileParams struct {
	ID          string
	Address     string
	Role        SupplyRole
	DisplayName *string
	Region      *string
	Now         time.Time
}

// Unlike UpsertRoleBinding, a repeated bind updates the profile fields that
// were provided and keeps the others.
func (q *Queries) UpsertRoleBindingProfile(ctx context.Context, arg UpsertRoleBindingProfileParams) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, upsertRoleBindingProfile,
		arg.ID,
		arg.Address,
		arg.Role,
		arg.DisplayName,
		arg.Region,
		arg.Now,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Region,
	)
	return i, err
}
