// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"
	"time"
)

const insertScanEvent = `-- name: InsertScanEvent :exec
INSERT INTO "ScanEvent" ("id", "batchId", "index", "deviceHash", "region", "statusAtScan", "riskScore", "createdAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertScanEventParams struct {
	ID           string
	BatchID      int64
	Index        int32
	DeviceHash   string
	Region       *string
	StatusAtScan string
	RiskScore    float64
	Now          time.Time
}

func (q *Queries) InsertScanEvent(ctx context.Context, arg InsertScanEventParams) error {
	_, err := q.db.Exec(ctx, insertScanEvent,
		arg.ID,
		arg.BatchID,
		arg.Index,
		arg.DeviceHash,
		arg.Region,
		arg.StatusAtScan,
		arg.RiskScore,
		arg.Now,
	)
	return err
}

const listSuspiciousUnits = `-- name: ListSuspiciousUnits :many
SELECT
    "batchId",
    "index",
    max("riskScore")::double precision AS max_risk,
    count(*)::integer AS scans,
    count(DISTINCT "deviceHash")::integer AS devices,
    max("createdAt")::timestamp AS last_scan_at
FROM "ScanEvent"
WHERE "createdAt" >= $1
GROUP BY "batchId", "index"
HAVING max("riskScore") >= $2::double precision
ORDER BY max_risk DESC, last_scan_at DESC
LIMIT $3
`

type ListSuspiciousUnitsParams struct {
	Since   time.Time
	MinRisk float64
	MaxRows int32
}

type ListSuspiciousUnitsRow struct {
	BatchID    int64
	Index      int32
	MaxRisk    float64
	Scans      int32
	Devices    int32
	LastScanAt time.Time
}

func (q *Queries) ListSuspiciousUnits(ctx context.Context, arg ListSuspiciousUnitsParams) ([]ListSuspiciousUnitsRow, error) {
	rows, err := q.db.Query(ctx, listSuspiciousUnits, arg.Since, arg.MinRisk, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuspiciousUnitsRow
	for rows.Next() {
		var i ListSuspiciousUnitsRow
		if err := rows.Scan(
			&i.BatchID,
			&i.Index,
			&i.MaxRisk,
			&i.Scans,
			&i.Devices,
			&i.LastScanAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScanRisk = `-- name: SetScanRisk :exec
UPDATE "ScanEvent" SET "riskScore" = $1, "statusAtScan" = $2 WHERE "id" = $3
`

type SetScanRiskParams struct {
	RiskScore    float64
	StatusAtScan string
	ID           string
}

// A scan is stored before it is scored so its own signal counts.
func (q *Queries) SetScanRisk(ctx context.Context, arg SetScanRiskParams) error {
	_, err := q.db.Exec(ctx, setScanRisk, arg.RiskScore, arg.StatusAtScan, arg.ID)
	return err
}

const unitScanSignals = `-- name: UnitScanSignals :one
WITH s AS (
    SELECT "deviceHash", "region", "createdAt" FROM "ScanEvent"
    WHERE "batchId" = $3 AND "index" = $4
),
before_consume AS (
    SELECT DISTINCT "deviceHash" FROM s
    WHERE $1::timestamp IS NULL OR "createdAt" <= $1::timestamp
)
SELECT
    (SELECT count(*) FROM s)::integer AS total_scans,
    (SELECT count(*) FROM before_consume)::integer AS devices_before_consume,
    (SELECT count(*) FROM s WHERE "createdAt" > $1::timestamp)::integer AS scans_after_consume,
    (SELECT count(DISTINCT "deviceHash") FROM s
        WHERE "createdAt" > $1::timestamp
          AND "deviceHash" NOT IN (SELECT "deviceHash" FROM before_consume))::integer AS new_devices_after_consume,
    (SELECT count(DISTINCT "region") FROM s WHERE "region" IS NOT NULL)::integer AS distinct_regions,
    (SELECT count(DISTINCT "region") FROM s
        WHERE "region" IS NOT NULL AND "region" <> $2::text)::integer AS foreign_regions
`

type UnitScanSignalsParams struct {
	ConsumedAt  *time.Time
	OwnerRegion *string
	BatchID     int64
	Index       int32
}

type UnitScanSignalsRow struct {
	TotalScans             int32
	DevicesBeforeConsume   int32
	ScansAfterConsume      int32
	NewDevicesAfterConsume int32
	DistinctRegions        int32
	ForeignRegions         int32
}

// Aggregates the clone-detection signals of one unit (see internal/risk,
// whose Signals/FromHistory compute the same values in memory).
func (q *Queries) UnitScanSignals(ctx context.Context, arg UnitScanSignalsParams) (UnitScanSignalsRow, error) {
	row := q.db.QueryRow(ctx, unitScanSignals,
		arg.ConsumedAt,
		arg.OwnerRegion,
		arg.BatchID,
		arg.Index,
	)
	var i UnitScanSignalsRow
	err := row.Scan(
		&i.TotalScans,
		&i.DevicesBeforeConsume,
		&i.ScansAfterConsume,
		&i.NewDevicesAfterConsume,
		&i.DistinctRegions,
		&i.ForeignRegions,
	)
	return i, err
}
