// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package db

import (
	"context"
	"time"
)

const countSegments = `-- name: CountSegments :one
SELECT count(*) FROM "Segment"
WHERE ($1::text IS NULL OR "owner" = $1)
  AND ($2::bigint IS NULL OR "batchId" = $2)
  AND ($3::"SegmentStatus" IS NULL OR "status" = $3)
`

type CountSegmentsParams struct {
	Owner   *string
	BatchID *int64
	Status  *SegmentStatus
}

func (q *Queries) CountSegments(ctx context.Context, arg CountSegmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSegments, arg.Owner, arg.BatchID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findSegmentForUnit = `-- name: FindSegmentForUnit :one
SELECT "segmentId", "batchId", owner, start, "end", status, "blockNumber", "logIndex", "createdAt", "updatedAt" FROM "Segment"
WHERE "batchId" = $1 AND "start" <= $2::integer AND "end" > $2::integer
ORDER BY "segmentId" ASC
LIMIT 1
`

type FindSegmentForUnitParams struct {
	BatchID int64
	Index   int32
}

func (q *Queries) FindSegmentForUnit(ctx context.Context, arg FindSegmentForUnitParams) (Segment, error) {
	row := q.db.QueryRow(ctx, findSegmentForUnit, arg.BatchID, arg.Index)
	var i Segment
	err := row.Scan(
		&i.SegmentID,
		&i.BatchID,
		&i.Owner,
		&i.Start,
		&i.End,
		&i.Status,
		&i.BlockNumber,
		&i.LogIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSegment = `-- name: GetSegment :one
SELECT "segmentId", "batchId", owner, start, "end", status, "blockNumber", "logIndex", "createdAt", "updatedAt" FROM "Segment" WHERE "segmentId" = $1
`

func (q *Queries) GetSegment(ctx context.Context, segmentID int64) (Segment, error) {
	row := q.db.QueryRow(ctx, getSegment, segmentID)
	var i Segment
	err := row.Scan(
		&i.SegmentID,
		&i.BatchID,
		&i.Owner,
		&i.Start,
		&i.End,
		&i.Status,
		&i.BlockNumber,
		&i.LogIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustodyEvent = `-- name: InsertCustodyEvent :exec
INSERT INTO "CustodyEvent" (
    "id", "batchId", "fromSegmentId", "toSegmentId", "fromAddress", "toAddress",
    "start", "end", "status", "txHash", "logIndex", "blockNumber", "createdAt"
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT ("txHash", "logIndex") DO NOTHING
`

type InsertCustodyEventParams struct {
	ID            string
	BatchID       int64
	FromSegmentID int64
	ToSegmentID   int64
	FromAddress   string
	ToAddress     string
	RangeStart    int32
	RangeEnd      int32
	Status        SegmentStatus
	TxHash        string
	LogIndex      int32
	BlockNumber   int64
	Now           time.Time
}

func (q *Queries) InsertCustodyEvent(ctx context.Context, arg InsertCustodyEventParams) error {
	_, err := q.db.Exec(ctx, insertCustodyEvent,
		arg.ID,
		arg.BatchID,
		arg.FromSegmentID,
		arg.ToSegmentID,
		arg.FromAddress,
		arg.ToAddress,
		arg.RangeStart,
		arg.RangeEnd,
		arg.Status,
		arg.TxHash,
		arg.LogIndex,
		arg.BlockNumber,
		arg.Now,
	)
	return err
}

const invalidateSegment = `-- name: InvalidateSegment :execrows
UPDATE "Segment"
SET "status" = 'Invalid', "blockNumber" = $1, "logIndex" = $2, "updatedAt" = $3
WHERE "segmentId" = $4
  AND ("blockNumber", "logIndex") < ($1::bigint, $2::integer)
`

type InvalidateSegmentParams struct {
	BlockNumber int64
	LogIndex    int32
	Now         time.Time
	SegmentID   int64
}

func (q *Queries) InvalidateSegment(ctx context.Context, arg InvalidateSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateSegment,
		arg.BlockNumber,
		arg.LogIndex,
		arg.Now,
		arg.SegmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBatchSegments = `-- name: ListBatchSegments :many
SELECT "segmentId", "batchId", owner, start, "end", status, "blockNumber", "logIndex", "createdAt", "updatedAt" FROM "Segment" WHERE "batchId" = $1 ORDER BY "start" ASC, "segmentId" ASC
`

func (q *Queries) ListBatchSegments(ctx context.Context, batchID int64) ([]Segment, error) {
	rows, err := q.db.Query(ctx, listBatchSegments, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.SegmentID,
			&i.BatchID,
			&i.Owner,
			&i.Start,
			&i.End,
			&i.Status,
			&i.BlockNumber,
			&i.LogIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegments = `-- name: ListSegments :many
SELECT "segmentId", "batchId", owner, start, "end", status, "blockNumber", "logIndex", "createdAt", "updatedAt" FROM "Segment"
WHERE ($1::text IS NULL OR "owner" = $1)
  AND ($2::bigint IS NULL OR "batchId" = $2)
  AND ($3::"SegmentStatus" IS NULL OR "status" = $3)
ORDER BY "batchId" DESC, "start" ASC, "segmentId" ASC
LIMIT $5 OFFSET $4
`

type ListSegmentsParams struct {
	Owner      *string
	BatchID    *int64
	Status     *SegmentStatus
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListSegments(ctx context.Context, arg ListSegmentsParams) ([]Segment, error) {
	rows, err := q.db.Query(ctx, listSegments,
		arg.Owner,
		arg.BatchID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.SegmentID,
			&i.BatchID,
			&i.Owner,
			&i.Start,
			&i.End,
			&i.Status,
			&i.BlockNumber,
			&i.LogIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitCustody = `-- name: ListUnitCustody :many
SELECT id, "batchId", "fromSegmentId", "toSegmentId", "fromAddress", "toAddress", start, "end", status, "txHash", "logIndex", "blockNumber", "createdAt" FROM "CustodyEvent"
WHERE "batchId" = $1 AND "start" <= $2::integer AND "end" > $2::integer
ORDER BY "blockNumber" ASC, "logIndex" ASC
`

type ListUnitCustodyParams struct {
	BatchID int64
	Index   int32
}

func (q *Queries) ListUnitCustody(ctx context.Context, arg ListUnitCustodyParams) ([]CustodyEvent, error) {
	rows, err := q.db.Query(ctx, listUnitCustody, arg.BatchID, arg.Index)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustodyEvent
	for rows.Next() {
		var i CustodyEvent
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.FromSegmentID,
			&i.ToSegmentID,
			&i.FromAddress,
			&i.ToAddress,
			&i.Start,
			&i.End,
			&i.Status,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveSegment = `-- name: MoveSegment :execrows
UPDATE "Segment"
SET "owner" = $1, "status" = $2, "blockNumber" = $3, "logIndex" = $4, "updatedAt" = $5
WHERE "segmentId" = $6
  AND ("blockNumber", "logIndex") < ($3::bigint, $4::integer)
`

type MoveSegmentParams struct {
	Owner       string
	Status      SegmentStatus
	BlockNumber int64
	LogIndex    int32
	Now         time.Time
	SegmentID   int64
}

func (q *Queries) MoveSegment(ctx context.Context, arg MoveSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveSegment,
		arg.Owner,
		arg.Status,
		arg.BlockNumber,
		arg.LogIndex,
		arg.Now,
		arg.SegmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putSegment = `-- name: PutSegment :exec

INSERT INTO "Segment" (
    "segmentId", "batchId", "owner", "start", "end", "status",
    "blockNumber", "logIndex", "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $9
)
ON CONFLICT ("segmentId") DO UPDATE SET
    "owner" = EXCLUDED."owner",
    "start" = GREATEST("Segment"."start", EXCLUDED."start"),
    "end" = EXCLUDED."end",
    "status" = EXCLUDED."status",
    "blockNumber" = EXCLUDED."blockNumber",
    "logIndex" = EXCLUDED."logIndex",
    "updatedAt" = EXCLUDED."updatedAt"
WHERE ("Segment"."blockNumber", "Segment"."logIndex") < (EXCLUDED."blockNumber", EXCLUDED."logIndex")
`

type PutSegmentParams struct {
	SegmentID   int64
	BatchID     int64
	Owner       string
	RangeStart  int32
	RangeEnd    int32
	Status      SegmentStatus
	BlockNumber int64
	LogIndex    int32
	Now         time.Time
}

// Segment writes carry the (blockNumber, logIndex) of the chain event they
// apply and are ignored when the row already reflects that event or a later one.
func (q *Queries) PutSegment(ctx context.Context, arg PutSegmentParams) error {
	_, err := q.db.Exec(ctx, putSegment,
		arg.SegmentID,
		arg.BatchID,
		arg.Owner,
		arg.RangeStart,
		arg.RangeEnd,
		arg.Status,
		arg.BlockNumber,
		arg.LogIndex,
		arg.Now,
	)
	return err
}

const shrinkSegment = `-- name: ShrinkSegment :execrows
UPDATE "Segment"
SET "start" = GREATEST("start", $1::integer), "updatedAt" = $2
WHERE "segmentId" = $3
`

type ShrinkSegmentParams struct {
	RangeStart int32
	Now        time.Time
	SegmentID  int64
}

// A split always moves the front of a segment, so "start" only grows. The
// shrink is therefore not position-guarded: it must still apply when a later
// move of the same segment was projected first (API receipt ahead of the
// indexer), and GREATEST keeps replays harmless.
func (q *Queries) ShrinkSegment(ctx context.Context, arg ShrinkSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, shrinkSegment, arg.RangeStart, arg.Now, arg.SegmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
