// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package db

import (
	"context"
	"time"
)

const getUnit = `-- name: GetUnit :one
SELECT "batchId", index, "unitKey", proof, consumer, "consumedTxHash", "consumedBlock", "consumedAt", "createdAt" FROM "Unit" WHERE "batchId" = $1 AND "index" = $2
`

type GetUnitParams struct {
	BatchID int64
	Index   int32
}

func (q *Queries) GetUnit(ctx context.Context, arg GetUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnit, arg.BatchID, arg.Index)
	var i Unit
	err := row.Scan(
		&i.BatchID,
		&i.Index,
		&i.UnitKey,
		&i.Proof,
		&i.Consumer,
		&i.ConsumedTxHash,
		&i.ConsumedBlock,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUnits = `-- name: InsertUnits :execrows
INSERT INTO "Unit" ("batchId", "index", "unitKey", "proof", "createdAt")
SELECT $1::bigint, unnest($2::integer[]), unnest($3::text[]), unnest($4::bytea[]), $5::timestamp
ON CONFLICT ("batchId", "index") DO UPDATE SET
    "proof" = COALESCE("Unit"."proof", EXCLUDED."proof")
`

type InsertUnitsParams struct {
	BatchID  int64
	Indexes  []int32
	UnitKeys []string
	Proofs   [][]byte
	Now      time.Time
}

func (q *Queries) InsertUnits(ctx context.Context, arg InsertUnitsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUnits,
		arg.BatchID,
		arg.Indexes,
		arg.UnitKeys,
		arg.Proofs,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUnits = `-- name: ListUnits :many
SELECT "batchId", "index", "unitKey", "consumer", "consumedTxHash", "consumedBlock", "consumedAt"
FROM "Unit"
WHERE "batchId" = $1
  AND ($2::boolean IS NULL OR ("consumedTxHash" IS NOT NULL) = $2)
ORDER BY "index" ASC
LIMIT $4 OFFSET $3
`

type ListUnitsParams struct {
	BatchID    int64
	Consumed   *bool
	PageOffset int32
	PageLimit  int32
}

type ListUnitsRow struct {
	BatchID        int64
	Index          int32
	UnitKey        string
	Consumer       *string
	ConsumedTxHash *string
	ConsumedBlock  *int64
	ConsumedAt     *time.Time
}

func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]ListUnitsRow, error) {
	rows, err := q.db.Query(ctx, listUnits,
		arg.BatchID,
		arg.Consumed,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitsRow
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(
			&i.BatchID,
			&i.Index,
			&i.UnitKey,
			&i.Consumer,
			&i.ConsumedTxHash,
			&i.ConsumedBlock,
			&i.ConsumedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnitConsumed = `-- name: MarkUnitConsumed :execrows
WITH changed AS (
    INSERT INTO "Unit" (
        "batchId", "index", "unitKey", "consumer", "consumedTxHash", "consumedBlock", "consumedAt", "createdAt"
    ) VALUES (
        $2, $3, $4, $5, $6, $7, $1, $1
    )
    ON CONFLICT ("batchId", "index") DO UPDATE SET
        "consumer" = EXCLUDED."consumer",
        "consumedTxHash" = EXCLUDED."consumedTxHash",
        "consumedBlock" = EXCLUDED."consumedBlock",
        "consumedAt" = EXCLUDED."consumedAt"
    WHERE "Unit"."consumedTxHash" IS NULL
    RETURNING "batchId"
)
UPDATE "Batch"
SET "consumedCount" = "consumedCount" + 1, "updatedAt" = $1
WHERE "batchId" IN (SELECT "batchId" FROM changed)
`

type MarkUnitConsumedParams struct {
	Now         time.Time
	BatchID     int64
	Index       int32
	UnitKey     string
	Consumer    *string
	TxHash      *string
	BlockNumber *int64
}

// Consumption is one-shot: only the first write for a unit counts towards
// the batch total, whichever of the API or the indexer gets there first.
func (q *Queries) MarkUnitConsumed(ctx context.Context, arg MarkUnitConsumedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUnitConsumed,
		arg.Now,
		arg.BatchID,
		arg.Index,
		arg.UnitKey,
		arg.Consumer,
		arg.TxHash,
		arg.BlockNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
